Set custom time marker type declaration fix
visjs/vis-timeline pull request #1659
Opened 2023-06-27 03:13 UTC by ryanrixxh

small fix for #1658

2023-08-29 03:53 UTC, jrsun approved these changes

2023-11-11 17:14 UTC, Thomaash requested changes
Hi @ryanrixxh, thanks for your contribution but you have an error in it. In TypeScript you can't have an optional parameter (`id`) precede a required parameter (`editable`). You either have to make editable optional too or make id required.

2024-01-09 13:01 UTC, thangvo-evn reviewed
LGTM

2025-06-24 18:27 UTC, mojoaxel commented
closing in favor of #1841

2025-06-24 18:27 UTC, closed without merging