improve xss security
visjs/vis-timeline pull request #840
Opened 2020-12-19 21:47 UTC by mojoaxel

I added the [xss library](https://www.npmjs.com/package/xss) to improve security.

fixes #838

2020-12-20 07:42 UTC, yotamberk commented on lib/shared/Popup.js
> +      this.frame.innerHTML = util.xss(content); // string containing text or HTML
util is not imported

2020-12-20 07:43 UTC, yotamberk requested changes
In some of the files `util` is not imported

2020-12-20 07:43 UTC, yotamberk commented on lib/timeline/component/CustomTime.js
> +    marker.innerHTML = util.xss(title);
here too

2020-12-20 09:33 UTC, mojoaxel commented on lib/shared/Popup.js
> +      this.frame.innerHTML = util.xss(content); // string containing text or HTML
fixed

2020-12-20 13:42 UTC, yotamberk approved these changes

2020-12-20 13:42 UTC, merged

2020-12-20 18:03 UTC, Donov4n commented
Hello :)

Its seems that this PR has introduced a regression because the `xss` dep. has only been added   
to devDeps and is therefore not available when consuming this vis-timeline.

The error : 

```
This dependency was not found:

* xss in ./node_modules/vis-timeline/esnext/esm/vis-timeline-graph2d.js

To install it, you can run: npm install --save xss
```

Should i open a new issue for this ?

2020-12-20 18:07 UTC, Thomaash commented
Hi there,

I know this is already out as a fix but this is a breaking change. XSS is basically nuking the HTML away with an extremely constrained set of exceptions. There are no forms, no classes, no styles etc. Also the thing has like 30K and for what? So that people can have the convenience of `<h2>Heading</h2><p>Text…</p>`? This doesn't seem worth it to me (though as always, this is up for discussion). If we really want to sanitize this and since we allow for HTMLElement to be used as a title, I would just use innerText for strings and changed the docs so that the people who want HTML in there would be instructed to pass HTMLElement (maybe using innerHTML there, if they choose to) instead of a string.

Another thing is that the configurator (which is except for reformatting identical to the code in Vis Network and really should be moved to Vis Util) doesn't really use HTML (apart from some simple wrapping, but we don't need innerHTML for that), it can be quite easily converted to innerText and no sanitation is necessary at all.

2020-12-20 22:14 UTC, mojoaxel commented
@Donov4n Sorry! 
@Thomaash Thanks!

2021-01-04 23:31 UTC, ckeboss commented
I agree with @Thomaash, shouldn't sanitization be up to the user?

For example, setting a tooltip template is now pretty useless, as you can not input any attributes to elements.