Locales: Swedish and Norwegian
visjs/vis-timeline pull request #891
Opened 2021-02-03 19:12 UTC by melloware

Requested from PrimeFaces ticket: https://github.com/primefaces/primefaces/issues/6932

2021-03-02 13:43 UTC, melloware commented
Any way we can get this merged and a release cut?

2021-03-17 11:03 UTC, mojoaxel requested changes

2021-03-17 11:03 UTC, mojoaxel commented on docs/timeline/index.html
> +        <code>pt_BR</code><br>
This merge request should only touch the Swedish and Norwegian parts and leave the other code alone for not. It Portuguese need change this should be done in a seperate merge request.

2021-03-17 11:04 UTC, mojoaxel commented
@melloware Thanks for this pull-request! Let's merge that soon!

2021-03-18 11:18 UTC, mojoaxel approved these changes
LGTM!

2021-03-28 10:24 UTC, yotamberk approved these changes

2021-03-28 10:24 UTC, merged